[profile.default]
solc = "0.8.17"
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
	{ access = "read-write", path = ".forge-snapshots/"},
	{ access = "read", path = "configs.json"}
]
optimizer_runs = 1_000_000
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
