[profile.default]
solc = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
optimizer_runs = 1000000

# [rpc_endpoints]
# eth 	= "${RPC_URL_ETH}"
# arb		= "${RPC_URL_ARB}"
# op		= "${RPC_URL_OP}"
# bnb 	= "${RPC_URL_BNB}"
# matic	= "${RPC_URL_MATIC}"
# ftm		= "${RPC_URL_FTM}"
# avax	= "${RPC_URL_AVAX}"
# 
# [etherscan]
# eth = { key = "${SCANNER_API_KEY_ETH}" }
# arb = { key = "${SCANNER_API_KEY_ARB}" }
# op = { key = "${SCANNER_API_KEY_OP}" }
# bnb = { key = "${SCANNER_API_KEY_BNB}" }
# matic = { key = "${SCANNER_API_KEY_MATIC}" }
# ftm = { key = "${SCANNER_API_KEY_FTM}" }
# avax = { key = "${SCANNER_API_KEY_AVAX}" }
# 
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


#	forge-gas-snapshot/=lib/forge-gas-snapshot/src/,
#	openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/,
#	permit2/=lib/permit2/,
#	solmate/=lib/solmate/,