#!/bin/zsh
set -euo pipefail

deployments=script/input/deployments.json

b=false; [[ " $* " == *" -b "* ]] && b=true

trap chain EXIT

chains=(eth arb bnb matic ftm op linea blast base zkevm manta sei sonic zircuit scroll)

echo $chains | tr ' ' '\n' | parallel --keep-order "
    echo \"\n🔗🔗🔗🔗🔗🔗🔗🔗🔗🔗🔗🔗 {} 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀\n\";
    chain {};

    export ADMIN=$(jq -r '."*".admin' $deployments);
    export REACTOR=$(jq -r '."*".reactor' $deployments);
    export REPERMIT=$(jq -r '."*".repermit' $deployments);

    #forge script DeployAdmin ${b:+--broadcast};
    echo \"✔ admin\n\"

    #forge script UpdateWhitelist ${b:+--broadcast};
    echo \"✔ whitelist\n\"

    #forge script DeployReactor ${b:+--broadcast};
    echo \"✔ reactor\n\"

    export SALT="0x0000000000000000000000000000000000000000000000000000000000000001"
    forge script DeployReactor ${b:+--broadcast};
    echo \"✔ reactor2\n\"

    forge script DeployExecutor ${b:+--broadcast};
    echo \"✔ executor\n\"

#    forge script DeployRepermit ${b:+--broadcast};
    echo \"✔ repermit\n\"

#    forge script DeployPartial ${b:+--broadcast};
    echo \"✔ partial\n\"
"
